-- Add 37 admin/pedagogical task types to the TaskType enum.
-- These are the numeric codes (TT_1_1 ... TT_8_4) used by the admin app,
-- defined in Дасгалын_төрлүүд_каталог_v3.xlsx.
-- The existing 42 pipeline types are unchanged.

ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_1_1';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_1_2';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_1_3';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_1_4';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_1_5';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_2_1';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_2_2';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_2_3';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_2_4';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_2_5';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_2_6';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_3_1';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_3_2';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_3_3';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_3_4';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_3_5';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_4_1';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_4_2';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_4_3';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_4_4';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_4_5';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_5_1';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_5_2';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_5_3';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_5_4';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_5_5';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_5_6';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_5_7';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_6_1';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_6_2';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_6_3';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_6_4';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_7_1';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_7_2';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_7_3';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_7_4';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_7_5';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_7_6';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_7_7';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_8_1';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_8_2';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_8_3';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'TT_8_4';
