import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";
import {
  PrismaClient,
  TaskType,
  SkillCode,
  LessonSlot,
} from "../generated/prisma";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

// ─── Word seed data ───────────────────────────────────────────
// Source: docs/0. Агуулгын бүтэц, тохиргоо.xlsx — Master_Asset_Bank sheet
// Columns: word_id, word, category, grade_band, char_count, syllable_count,
//          skill_tags, error_tags, image_ok, audio_ok, image_prompt, audio_text,
//          sample_sentence, distractors, blank_hint

function parseGradeBand(raw: string): string[] {
  if (raw.includes("-")) return raw.split("-");
  return [raw];
}

function parseStringArray(raw: string, sep = ","): string[] {
  return raw
    .split(sep)
    .map((s) => s.trim())
    .filter(Boolean);
}

// Filter out invalid skill tags (only S1-S8 are valid enum values)
function parseSkillTags(raw: string): string[] {
  const valid = new Set(["S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8"]);
  return parseStringArray(raw).filter((s) => valid.has(s));
}

const wordRows = [
  [
    "W001",
    "ном",
    "Нэр үг",
    "G1",
    "3",
    "1",
    "S1,S2",
    "A2,B1",
    "1",
    "1",
    "цагаан дэвсгэр дээр ганц ном, хүүхдэд ойлгомжтой энгийн зураг",
    "ном",
    "Энэ бол ном.",
    "нум; мод",
    "н_м",
  ],
  [
    "W002",
    "нум",
    "Нэр үг",
    "G1",
    "3",
    "1",
    "S1,S2",
    "A1,A2",
    "1",
    "1",
    "цагаан дэвсгэр дээр нум сумгүйгээр, энгийн дүрслэл",
    "нум",
    "Нум өлгөөтэй байна.",
    "ном; нуур",
    "н_м",
  ],
  [
    "W003",
    "мод",
    "Нэр үг",
    "G1",
    "3",
    "1",
    "S1,S2",
    "A1,B1",
    "1",
    "1",
    "ногоон навчтай ганц мод",
    "мод",
    "Хашаанд мод байна.",
    "ном; мол",
    "м_д",
  ],
  [
    "W004",
    "гэр",
    "Нэр үг",
    "G1",
    "4",
    "1",
    "S2,S7",
    "B1,D5",
    "1",
    "1",
    "монгол гэрийг урдаас харуулсан энгийн зураг",
    "гэр",
    "Дулаахан гэр.",
    "гар; гөл",
    "гэ_",
  ],
  [
    "W005",
    "нар",
    "Нэр үг",
    "G1",
    "3",
    "1",
    "S1,S2",
    "A1,D5",
    "1",
    "1",
    "инээмсэглэсэн биш, энгийн шар нар",
    "нар",
    "Нар мандлаа.",
    "сар; нур",
    "н_р",
  ],
  [
    "W006",
    "сар",
    "Нэр үг",
    "G1",
    "3",
    "1",
    "S1,S2",
    "A1,D5",
    "1",
    "1",
    "шөнийн тэнгэргүйгээр ганц хавирган сар",
    "сар",
    "Сар тод байна.",
    "нар; сор",
    "с_р",
  ],
  [
    "W007",
    "ус",
    "Нэр үг",
    "G1",
    "2",
    "1",
    "S1,S2",
    "A1",
    "1",
    "1",
    "устай аяга эсвэл усны дусал",
    "ус",
    "Ус тунгалаг.",
    "үс; үнс",
    "_с",
  ],
  [
    "W008",
    "цас",
    "Нэр үг",
    "G1",
    "3",
    "1",
    "S2,S3",
    "B1,C1",
    "1",
    "1",
    "цагаан цасан овоо",
    "цас",
    "Цас орлоо.",
    "цэц; тас",
    "ц_с",
  ],
  [
    "W009",
    "мал",
    "Нэр үг",
    "G1",
    "3",
    "1",
    "S2,S5",
    "B1,E1",
    "1",
    "1",
    "малын ерөнхий энгийн дүрс, олон амьтан биш",
    "мал",
    "Мал бэлчинэ.",
    "малд; мол",
    "м_л",
  ],
  [
    "W010",
    "гал",
    "Нэр үг",
    "G1",
    "3",
    "1",
    "S1,S2",
    "A1,B1",
    "1",
    "1",
    "аюулгүй, жижиг галын дөл",
    "гал",
    "Гал дүрэлзэв.",
    "гар; гол",
    "г_л",
  ],
  [
    "W011",
    "тогоо",
    "Нэр үг",
    "G1-G2",
    "5",
    "2",
    "S3,S2",
    "C1,C2",
    "1",
    "1",
    "гал дээр биш, ганц тогоо",
    "тогоо",
    "Тогоо том.",
    "того; тогуу",
    "т_г_о",
  ],
  [
    "W012",
    "бөмбөг",
    "Нэр үг",
    "G1-G2",
    "6",
    "2",
    "S2,S3",
    "B1,C1",
    "1",
    "1",
    "улаан бөмбөг, цагаан дэвсгэртэй",
    "бөмбөг",
    "Би бөмбөг шидэв.",
    "бөмбөгг; бөмбөгө",
    "бөмб_г",
  ],
  [
    "W013",
    "шувуу",
    "Нэр үг",
    "G1-G2",
    "6",
    "2",
    "S3,S2",
    "C1,C2",
    "1",
    "1",
    "ганц жижиг шувуу",
    "шувуу",
    "Шувуу нисэв.",
    "шуву; шувүү",
    "шув_у",
  ],
  [
    "W014",
    "хүүхэд",
    "Нэр үг",
    "G1-G2",
    "6",
    "2",
    "S2,S3",
    "B3,C4",
    "1",
    "1",
    "хүүхэд ганцаараа зогсож буй энгийн зураг",
    "хүүхэд",
    "Хүүхэд инээв.",
    "хүүхэдд; хүүхд",
    "хүү_эд",
  ],
  [
    "W015",
    "цэцэг",
    "Нэр үг",
    "G1-G2",
    "6",
    "2",
    "S2,S3",
    "B1,C1",
    "1",
    "1",
    "ганц цэцэг, энгийн дүрс",
    "цэцэг",
    "Цэцэг ургав.",
    "цэцэгг; цэцэгө",
    "цэц_г",
  ],
  [
    "W016",
    "авдар",
    "Нэр үг",
    "G2",
    "6",
    "2",
    "S4,S2",
    "C4,D5",
    "1",
    "1",
    "модон авдар, урдаас харсан",
    "авдар",
    "Авдар өрөөнд байна.",
    "авдр; автар",
    "авд_р",
  ],
  [
    "W017",
    "өндөг",
    "Нэр үг",
    "G1-G2",
    "5",
    "2",
    "S3,S2",
    "C1,D5",
    "1",
    "1",
    "ганц өндөг эсвэл хоёр өндөг",
    "өндөг",
    "Өндөг чанав.",
    "өндөгг; өнд_г",
    "өнд_г",
  ],
  [
    "W018",
    "дэвтэр",
    "Нэр үг",
    "G1-G2",
    "7",
    "2",
    "S4,S2",
    "C4,D5",
    "1",
    "1",
    "хаалттай дэвтэр",
    "дэвтэр",
    "Дэвтэр цэвэр.",
    "дэвтр; дэвтэрр",
    "дэвт_р",
  ],
  [
    "W019",
    "сандал",
    "Нэр үг",
    "G1-G2",
    "7",
    "2",
    "S4,S2",
    "C4,D5",
    "1",
    "1",
    "ганц сандал, хажуу талаас",
    "сандал",
    "Сандал модон.",
    "сандл; сандалд",
    "санд_л",
  ],
  [
    "W020",
    "цонх",
    "Нэр үг",
    "G1-G2",
    "4",
    "1",
    "S2,S4",
    "B1,C4",
    "1",
    "1",
    "байшингийн ганц цонх",
    "цонх",
    "Цонх нээлттэй.",
    "цонхх; цон_",
    "цон_",
  ],
  [
    "W021",
    "харандаа",
    "Нэр үг",
    "G2",
    "8",
    "3",
    "S4,S2",
    "C4,B3",
    "1",
    "1",
    "шар харандаа ганцаараа",
    "харандаа",
    "Харандаа хурц.",
    "харанда; харандааа",
    "харанд_а",
  ],
  [
    "W022",
    "сүү",
    "Нэр үг",
    "G1-G2",
    "3",
    "1",
    "S3,S7",
    "C1,H1",
    "1",
    "1",
    "шилэн аягатай сүү",
    "сүү",
    "Сүү цагаан.",
    "су; сү",
    "с_ү",
  ],
  [
    "W023",
    "алим",
    "Нэр үг",
    "G1-G2",
    "4",
    "2",
    "S2,S7",
    "B1,H1",
    "1",
    "1",
    "улаан алим ганцаараа",
    "алим",
    "Алим амттай.",
    "алимм; ал_м",
    "ал_м",
  ],
  [
    "W024",
    "гутал",
    "Нэр үг",
    "G1-G2",
    "5",
    "2",
    "S2,S7",
    "B1,H1",
    "1",
    "1",
    "хос гутал",
    "гутал",
    "Гутал цэвэр.",
    "гутл; гуталл",
    "гут_л",
  ],
  [
    "W025",
    "туулай",
    "Нэр үг",
    "G2",
    "6",
    "2",
    "S3,S2",
    "C1,B1",
    "1",
    "1",
    "цагаан туулай ганцаараа",
    "туулай",
    "Туулай хурдан.",
    "туулайй; тулай",
    "т_улай",
  ],
  [
    "W026",
    "багш",
    "Нэр үг",
    "G2",
    "5",
    "1",
    "S2,S6",
    "B1,G1",
    "1",
    "1",
    "багш самбарын өмнө биш, энгийн хөрөг маягаар",
    "багш",
    "Багш ирлээ.",
    "багш.",
    "баг_",
  ],
  [
    "W027",
    "сургууль",
    "Нэр үг",
    "G2",
    "8",
    "2",
    "S5,S6",
    "E1,G1",
    "1",
    "1",
    "сургуулийн барилгын энгийн зураг",
    "сургууль",
    "Сургууль эхэллээ.",
    "сургуули; сургуль",
    "сургуу_ь",
  ],
  [
    "W028",
    "хоол",
    "Нэр үг",
    "G1-G2",
    "4",
    "1",
    "S3,S5",
    "C1,E1",
    "1",
    "1",
    "уур савссан аяга хоол",
    "хоол",
    "Хоол халуун.",
    "хол; хоолл",
    "х_ол",
  ],
  [
    "W029",
    "ээж",
    "Нэр үг",
    "G1-G2",
    "3",
    "1",
    "S3,S6",
    "C1,G1",
    "1",
    "1",
    "ээж инээмсэглэж зогсож буй энгийн зураг",
    "ээж",
    "Ээж ирэв.",
    "эж; ээж.",
    "_эж",
  ],
  [
    "W030",
    "аав",
    "Нэр үг",
    "G1-G2",
    "3",
    "1",
    "S3,S6",
    "C1,G1",
    "1",
    "1",
    "аав энгийн хөрөг",
    "аав",
    "Аав ажиллав.",
    "ав; аав.",
    "_ав",
  ],
  [
    "W031",
    "Бат",
    "Оноосон нэр",
    "G2",
    "3",
    "1",
    "S6",
    "G1",
    "0",
    "1",
    "зураг хэрэглэхгүй",
    "Бат",
    "Бат ирлээ.",
    "бат",
    "Б_т",
  ],
  [
    "W032",
    "би явна",
    "Богино өгүүлбэр",
    "G1-G2",
    "7",
    "3",
    "S6",
    "G1,G2",
    "0",
    "1",
    "зураг хэрэглэхгүй",
    "Би явна.",
    "Би явна.",
    "би явна",
    "би явна",
  ],
  [
    "W033",
    "тэр ирэв",
    "Богино өгүүлбэр",
    "G1-G2",
    "8",
    "3",
    "S6",
    "G1,G2",
    "0",
    "1",
    "зураг хэрэглэхгүй",
    "Тэр ирэв.",
    "Тэр ирэв.",
    "тэр ирэв",
    "тэр ирэв",
  ],
  [
    "W034",
    "номоо",
    "Залгавартай үг",
    "G2",
    "5",
    "2",
    "S5",
    "E1,E2",
    "0",
    "1",
    "зураг хэрэглэхгүй",
    "номоо",
    "Би номоо авлаа.",
    "номо; номаа",
    "ном_о",
  ],
  [
    "W035",
    "гэрт",
    "Залгавартай үг",
    "G2",
    "4",
    "1",
    "S5",
    "E1,E2",
    "0",
    "1",
    "зураг хэрэглэхгүй",
    "гэрт",
    "Би гэртээ байна.",
    "гэрд; гэр",
    "гэр_",
  ],
  [
    "W036",
    "морь",
    "Нэр үг",
    "G1-G2",
    "4",
    "1",
    "S2",
    "B1,D5",
    "1",
    "1",
    "ганц морь, хажуу талаас",
    "морь",
    "Морь хурдан.",
    "мор; морй",
    "мор_",
  ],
  [
    "W037",
    "тоног",
    "Нэр үг",
    "G2",
    "5",
    "2",
    "S2",
    "D5",
    "0",
    "1",
    "зураг шаардлагагүй",
    "тоног",
    "Тоног бэлэн.",
    "тонод; тоногг",
    "тоно_",
  ],
  [
    "W038",
    "хивс",
    "Нэр үг",
    "G2",
    "5",
    "1",
    "S2",
    "D5",
    "1",
    "1",
    "ганц хивс дээрээс биш, бага өнцгөөр",
    "хивс",
    "Хивс цэвэр.",
    "хив; хивсс",
    "хив_",
  ],
  [
    "W039",
    "зураг",
    "Нэр үг",
    "G1-G2",
    "5",
    "2",
    "S2",
    "B1,D5",
    "1",
    "1",
    "хананд өлгөсөн ганц зураг",
    "зураг",
    "Зураг гоё.",
    "зурак; зура",
    "зура_",
  ],
  [
    "W040",
    "сав",
    "Нэр үг",
    "G1",
    "3",
    "1",
    "S1,S2",
    "A1,B1",
    "1",
    "1",
    "ганц сав",
    "сав",
    "Сав хоосон.",
    "сар; сов",
    "с_в",
  ],
] as const;

// ─── Task seed data ───────────────────────────────────────────
// Source: docs/0. Агуулгын бүтэц, тохиргоо.xlsx — Sample_Assembled_Tasks sheet
// 20 tasks, deduplicated IDs using suffix for variants

interface TaskSeed {
  id: string;
  task_type: TaskType;
  title: string;
  prompt_text: string;
  correct_answer: string;
  options: object;
  audio_url: string | null;
  image_url: string | null;
  primary_skill: SkillCode;
  secondary_skill: SkillCode | null;
  level_target: string;
  error_targets: string[];
  grade_band: string[];
  difficulty: number;
  estimated_time_seconds: number;
  review_after_days: number[];
  lesson_slot_fit: LessonSlot;
  feedback_text: string;
}

const tasks: TaskSeed[] = [
  // G12-001a — TT1 Choice: Listen and pick "ном"
  {
    id: "G12-001a",
    task_type: TaskType.TT1_CHOICE,
    title: "Сонсож сонгох — ном",
    prompt_text: "Сонслоо. Аль үг вэ?",
    correct_answer: "ном",
    options: {
      choices: [
        { text: "ном", is_correct: true },
        { text: "нум", is_correct: false },
        { text: "мод", is_correct: false },
      ],
      audio_trigger: true,
    },
    audio_url: null,
    image_url: null,
    primary_skill: SkillCode.S1,
    secondary_skill: SkillCode.S2,
    level_target: "M0",
    error_targets: ["A2", "B1"],
    grade_band: ["G1"],
    difficulty: 1,
    estimated_time_seconds: 30,
    review_after_days: [1, 3, 7],
    lesson_slot_fit: LessonSlot.WARM_UP,
    feedback_text: "'ном' гэдэг үгэнд о авиаг сонслоо.",
  },
  // G12-001b — TT1 Choice: Listen and pick "сар"
  {
    id: "G12-001b",
    task_type: TaskType.TT1_CHOICE,
    title: "Сонсож сонгох — сар",
    prompt_text: "Сонслоо. Аль үг вэ?",
    correct_answer: "сар",
    options: {
      choices: [
        { text: "сар", is_correct: true },
        { text: "нар", is_correct: false },
        { text: "сав", is_correct: false },
      ],
      audio_trigger: true,
    },
    audio_url: null,
    image_url: null,
    primary_skill: SkillCode.S1,
    secondary_skill: SkillCode.S2,
    level_target: "M0",
    error_targets: ["A1", "D5"],
    grade_band: ["G1"],
    difficulty: 1,
    estimated_time_seconds: 30,
    review_after_days: [1, 3, 7],
    lesson_slot_fit: LessonSlot.WARM_UP,
    feedback_text: "Зөв сонслоо.",
  },
  // G12-002 — TT2 Fill: н_м → о
  {
    id: "G12-002",
    task_type: TaskType.TT2_FILL,
    title: "Үсэг нөхөх — ном",
    prompt_text: "Дутуу үсгийг нөх.",
    correct_answer: "о",
    options: {
      display_text: "н_м",
      blank_position: 1,
      blank_answer: "о",
      context_word: "ном",
    },
    audio_url: null,
    image_url: null,
    primary_skill: SkillCode.S2,
    secondary_skill: SkillCode.S1,
    level_target: "M0",
    error_targets: ["A2"],
    grade_band: ["G1"],
    difficulty: 1,
    estimated_time_seconds: 45,
    review_after_days: [1, 3, 7],
    lesson_slot_fit: LessonSlot.CORE,
    feedback_text: "'ном' гэж бүтэн уншаад шалга.",
  },
  // G12-003a — TT1 Choice: image → алим
  {
    id: "G12-003a",
    task_type: TaskType.TT1_CHOICE,
    title: "Зураг-үг тааруулах — алим",
    prompt_text: "Зургийг үгтэй тааруул.",
    correct_answer: "алим",
    options: {
      choices: [
        { text: "алим", is_correct: true },
        { text: "гутал", is_correct: false },
        { text: "цас", is_correct: false },
      ],
      audio_trigger: false,
    },
    audio_url: null,
    image_url: null,
    primary_skill: SkillCode.S2,
    secondary_skill: SkillCode.S7,
    level_target: "M0-M1",
    error_targets: ["B1", "H1"],
    grade_band: ["G1", "G2"],
    difficulty: 2,
    estimated_time_seconds: 40,
    review_after_days: [1, 3, 7],
    lesson_slot_fit: LessonSlot.WARM_UP,
    feedback_text: "Зурагтай үгийг зөв таарууллаа.",
  },
  // G12-003b — TT1 Choice: image → гэр
  {
    id: "G12-003b",
    task_type: TaskType.TT1_CHOICE,
    title: "Зураг-үг тааруулах — гэр",
    prompt_text: "Зургийг үгтэй тааруул.",
    correct_answer: "гэр",
    options: {
      choices: [
        { text: "гэр", is_correct: true },
        { text: "морь", is_correct: false },
        { text: "ном", is_correct: false },
      ],
      audio_trigger: false,
    },
    audio_url: null,
    image_url: null,
    primary_skill: SkillCode.S2,
    secondary_skill: SkillCode.S7,
    level_target: "M0",
    error_targets: ["B1", "D5"],
    grade_band: ["G1"],
    difficulty: 1,
    estimated_time_seconds: 40,
    review_after_days: [1, 3, 7],
    lesson_slot_fit: LessonSlot.WARM_UP,
    feedback_text: "Зураг нь монгол гэр байна.",
  },
  // G12-004 — TT4 Dictation: copy "Энэ бол ном."
  {
    id: "G12-004",
    task_type: TaskType.TT4_DICTATION,
    title: "Хуулж бичих — Энэ бол ном.",
    prompt_text: "Доорх өгүүлбэрийг бич.",
    correct_answer: "Энэ бол ном.",
    options: {
      audio_text: "Энэ бол ном.",
      word_count: 3,
      expected_answers: ["Энэ бол ном."],
      allow_partial: false,
    },
    audio_url: null,
    image_url: null,
    primary_skill: SkillCode.S7,
    secondary_skill: SkillCode.S6,
    level_target: "M1",
    error_targets: ["G1", "G2"],
    grade_band: ["G1"],
    difficulty: 2,
    estimated_time_seconds: 60,
    review_after_days: [1, 3, 7],
    lesson_slot_fit: LessonSlot.CORE,
    feedback_text: "Үсгийн дараалал, цэгээ шалга.",
  },
  // G12-005a — TT1 Choice: тогоо correct spelling
  {
    id: "G12-005a",
    task_type: TaskType.TT1_CHOICE,
    title: "Зөвийг сонгох — тогоо",
    prompt_text: "Аль нь зөв бичсэн үг вэ?",
    correct_answer: "тогоо",
    options: {
      choices: [
        { text: "тогоо", is_correct: true },
        { text: "того", is_correct: false },
        { text: "тогуу", is_correct: false },
      ],
      audio_trigger: false,
    },
    audio_url: null,
    image_url: null,
    primary_skill: SkillCode.S3,
    secondary_skill: SkillCode.S2,
    level_target: "M1",
    error_targets: ["C1", "C2"],
    grade_band: ["G1", "G2"],
    difficulty: 2,
    estimated_time_seconds: 35,
    review_after_days: [1, 3, 7],
    lesson_slot_fit: LessonSlot.CORE,
    feedback_text: "Урт эгшгийг анзаар.",
  },
  // G12-005b — TT1 Choice: сүү correct spelling
  {
    id: "G12-005b",
    task_type: TaskType.TT1_CHOICE,
    title: "Зөвийг сонгох — сүү",
    prompt_text: "Аль нь зөв бичсэн үг вэ?",
    correct_answer: "сүү",
    options: {
      choices: [
        { text: "сүү", is_correct: true },
        { text: "су", is_correct: false },
        { text: "сү", is_correct: false },
      ],
      audio_trigger: false,
    },
    audio_url: null,
    image_url: null,
    primary_skill: SkillCode.S3,
    secondary_skill: SkillCode.S7,
    level_target: "M1",
    error_targets: ["C1", "H1"],
    grade_band: ["G1", "G2"],
    difficulty: 2,
    estimated_time_seconds: 35,
    review_after_days: [1, 3, 7],
    lesson_slot_fit: LessonSlot.CORE,
    feedback_text: "Урт эгшигтэй хэлбэрийг сонго.",
  },
  // G12-006a — TT2 Fill: бөмб_г → ө
  {
    id: "G12-006a",
    task_type: TaskType.TT2_FILL,
    title: "Нөхөж бичих — бөмбөг",
    prompt_text: "Дутуу үсгийг нөх.",
    correct_answer: "ө",
    options: {
      display_text: "бөмб_г",
      blank_position: 4,
      blank_answer: "ө",
      context_word: "бөмбөг",
    },
    audio_url: null,
    image_url: null,
    primary_skill: SkillCode.S2,
    secondary_skill: SkillCode.S3,
    level_target: "M1",
    error_targets: ["B1", "C1"],
    grade_band: ["G1", "G2"],
    difficulty: 2,
    estimated_time_seconds: 45,
    review_after_days: [1, 3, 7],
    lesson_slot_fit: LessonSlot.CORE,
    feedback_text: "Дундах эгшгийг зөв нөх.",
  },
  // G12-006b — TT2 Fill: шув_у → у
  {
    id: "G12-006b",
    task_type: TaskType.TT2_FILL,
    title: "Нөхөж бичих — шувуу",
    prompt_text: "Дутуу үсгийг нөх.",
    correct_answer: "у",
    options: {
      display_text: "шув_у",
      blank_position: 3,
      blank_answer: "у",
      context_word: "шувуу",
    },
    audio_url: null,
    image_url: null,
    primary_skill: SkillCode.S3,
    secondary_skill: SkillCode.S2,
    level_target: "M1",
    error_targets: ["C1", "C2"],
    grade_band: ["G1", "G2"],
    difficulty: 2,
    estimated_time_seconds: 45,
    review_after_days: [1, 3, 7],
    lesson_slot_fit: LessonSlot.CORE,
    feedback_text: "Давхар эгшгийн хэлбэрийг анзаар.",
  },
  // G12-007 — TT2 Fill: дэвт_р (with audio), reduced vowel
  {
    id: "G12-007",
    task_type: TaskType.TT2_FILL,
    title: "Дутуу үсэг — дэвтэр",
    prompt_text: "Аудио сонсоод дутуу үсгийг нөх.",
    correct_answer: "э",
    options: {
      display_text: "дэвт_р",
      blank_position: 4,
      blank_answer: "э",
      context_word: "дэвтэр",
    },
    audio_url: null,
    image_url: null,
    primary_skill: SkillCode.S4,
    secondary_skill: SkillCode.S2,
    level_target: "M1-M2",
    error_targets: ["C4", "D5"],
    grade_band: ["G1", "G2"],
    difficulty: 3,
    estimated_time_seconds: 50,
    review_after_days: [1, 3, 7],
    lesson_slot_fit: LessonSlot.CORE,
    feedback_text: "Балархай эгшгийг нөхөж бич.",
  },
  // G12-008 — TT4 Dictation: word set ном, гэр, нар
  {
    id: "G12-008",
    task_type: TaskType.TT4_DICTATION,
    title: "Үгийн багц диктант",
    prompt_text: "Сонсоод гурван үгийг бич.",
    correct_answer: "ном; гэр; нар",
    options: {
      audio_text: "ном, гэр, нар",
      word_count: 3,
      expected_answers: ["ном", "гэр", "нар"],
      allow_partial: true,
    },
    audio_url: null,
    image_url: null,
    primary_skill: SkillCode.S7,
    secondary_skill: SkillCode.S2,
    level_target: "M1",
    error_targets: ["B1", "H1"],
    grade_band: ["G1"],
    difficulty: 2,
    estimated_time_seconds: 90,
    review_after_days: [1, 3, 7],
    lesson_slot_fit: LessonSlot.CORE,
    feedback_text: "Сонссон дарааллаар бичээрэй.",
  },
  // G12-009a — TT3 Correction: capitalization + period
  {
    id: "G12-009a",
    task_type: TaskType.TT3_CORRECTION,
    title: "Том үсэг, цэг — би явна",
    prompt_text: "Алдааг засаад зөв бич.",
    correct_answer: "Би явна.",
    options: {
      incorrect_text: "би явна",
      correct_text: "Би явна.",
      error_type: "G1",
      hint: "Эхний үсэг том, төгсгөлд цэг.",
    },
    audio_url: null,
    image_url: null,
    primary_skill: SkillCode.S6,
    secondary_skill: null,
    level_target: "M1-M2",
    error_targets: ["G1", "G2"],
    grade_band: ["G1", "G2"],
    difficulty: 2,
    estimated_time_seconds: 60,
    review_after_days: [1, 3, 7],
    lesson_slot_fit: LessonSlot.CORE,
    feedback_text: "Эхний үсэг том, төгсгөлд цэг.",
  },
  // G12-009b — TT3 Correction: proper name capitalization
  {
    id: "G12-009b",
    task_type: TaskType.TT3_CORRECTION,
    title: "Том үсэг — бат ирлээ",
    prompt_text: "Алдааг засаад зөв бич.",
    correct_answer: "Бат ирлээ.",
    options: {
      incorrect_text: "бат ирлээ",
      correct_text: "Бат ирлээ.",
      error_type: "G1",
      hint: "Нэрний эхний үсэг том.",
    },
    audio_url: null,
    image_url: null,
    primary_skill: SkillCode.S6,
    secondary_skill: null,
    level_target: "M2",
    error_targets: ["G1"],
    grade_band: ["G2"],
    difficulty: 2,
    estimated_time_seconds: 60,
    review_after_days: [1, 3, 7],
    lesson_slot_fit: LessonSlot.CORE,
    feedback_text: "Нэрний эхний үсэг том.",
  },
  // G12-010 — TT1 Choice: suffix гэрт
  {
    id: "G12-010",
    task_type: TaskType.TT1_CHOICE,
    title: "Энгийн залгавар — гэрт",
    prompt_text: "Аль нь зөв хэлбэр вэ?",
    correct_answer: "гэрт",
    options: {
      choices: [
        { text: "гэрт", is_correct: true },
        { text: "гэрд", is_correct: false },
        { text: "гэр", is_correct: false },
      ],
      audio_trigger: false,
    },
    audio_url: null,
    image_url: null,
    primary_skill: SkillCode.S5,
    secondary_skill: SkillCode.S2,
    level_target: "M2",
    error_targets: ["E1", "E2"],
    grade_band: ["G2"],
    difficulty: 3,
    estimated_time_seconds: 40,
    review_after_days: [1, 3, 7],
    lesson_slot_fit: LessonSlot.CORE,
    feedback_text: "Түгээмэл залгаврын хэлбэрийг тань.",
  },
  // G12-011a — TT3 Correction: extra letter "номм"
  {
    id: "G12-011a",
    task_type: TaskType.TT3_CORRECTION,
    title: "Алдаа олох — номм",
    prompt_text: "Алдаатай үгийг засаж бич.",
    correct_answer: "ном",
    options: {
      incorrect_text: "номм",
      correct_text: "ном",
      error_type: "B4",
      hint: "Илүү үсгийг хас.",
    },
    audio_url: null,
    image_url: null,
    primary_skill: SkillCode.S8,
    secondary_skill: SkillCode.S2,
    level_target: "M1",
    error_targets: ["B1"],
    grade_band: ["G1", "G2"],
    difficulty: 2,
    estimated_time_seconds: 50,
    review_after_days: [1, 3, 7],
    lesson_slot_fit: LessonSlot.END,
    feedback_text: "Илүү үсгийг хас.",
  },
  // G12-011b — TT3 Correction: missing long vowel "того"
  {
    id: "G12-011b",
    task_type: TaskType.TT3_CORRECTION,
    title: "Алдаа олох — того",
    prompt_text: "Алдаатай үгийг засаж бич.",
    correct_answer: "тогоо",
    options: {
      incorrect_text: "того",
      correct_text: "тогоо",
      error_type: "C1",
      hint: "Урт эгшгийг дутуу бичсэн байна.",
    },
    audio_url: null,
    image_url: null,
    primary_skill: SkillCode.S8,
    secondary_skill: SkillCode.S3,
    level_target: "M1-M2",
    error_targets: ["C1"],
    grade_band: ["G1", "G2"],
    difficulty: 3,
    estimated_time_seconds: 50,
    review_after_days: [1, 3, 7],
    lesson_slot_fit: LessonSlot.END,
    feedback_text: "Урт эгшгийг дутуу бичсэн байна.",
  },
  // G12-012 — TT6 Self-check: сү → сүү
  {
    id: "G12-012",
    task_type: TaskType.TT6_SELF_CHECK,
    title: "Өөрийгөө шалгах — сүү",
    prompt_text: "Өөрийн хариуг загвартай харьцуулаад шалга.",
    correct_answer: "сүү",
    options: {
      original_attempt: "сү",
      model_answer: "сүү",
      comparison_mode: "side_by_side",
    },
    audio_url: null,
    image_url: null,
    primary_skill: SkillCode.S8,
    secondary_skill: SkillCode.S3,
    level_target: "M1",
    error_targets: ["C1", "H1"],
    grade_band: ["G1", "G2"],
    difficulty: 2,
    estimated_time_seconds: 60,
    review_after_days: [1, 3, 7],
    lesson_slot_fit: LessonSlot.END,
    feedback_text: "Хоёр үсгийн ялгааг өөрөө ол.",
  },
  // G12-013 — TT4 Dictation: 2-word dictation
  {
    id: "G12-013",
    task_type: TaskType.TT4_DICTATION,
    title: "2 үгийн диктант — ном, сар",
    prompt_text: "Сонсоод хоёр үгийг бич.",
    correct_answer: "ном; сар",
    options: {
      audio_text: "ном, сар",
      word_count: 2,
      expected_answers: ["ном", "сар"],
      allow_partial: true,
    },
    audio_url: null,
    image_url: null,
    primary_skill: SkillCode.S7,
    secondary_skill: SkillCode.S2,
    level_target: "M0-M1",
    error_targets: ["B1", "H1"],
    grade_band: ["G1"],
    difficulty: 1,
    estimated_time_seconds: 60,
    review_after_days: [1, 3, 7],
    lesson_slot_fit: LessonSlot.MIXED,
    feedback_text: "Хоёр үгийг дарааллаар нь бич.",
  },
  // G12-014 — TT2 Fill: гэ_ → р (word ending)
  {
    id: "G12-014",
    task_type: TaskType.TT2_FILL,
    title: "Үгийн төгсгөл — гэр",
    prompt_text: "Дутуу үсгийг нөх.",
    correct_answer: "р",
    options: {
      display_text: "гэ_",
      blank_position: 2,
      blank_answer: "р",
      context_word: "гэр",
    },
    audio_url: null,
    image_url: null,
    primary_skill: SkillCode.S2,
    secondary_skill: SkillCode.S7,
    level_target: "M0",
    error_targets: ["B1", "D5"],
    grade_band: ["G1"],
    difficulty: 1,
    estimated_time_seconds: 40,
    review_after_days: [1, 3, 7],
    lesson_slot_fit: LessonSlot.WARM_UP,
    feedback_text: "Төгсгөлийн үсгийг зөв бич.",
  },
];

// ─── Main ─────────────────────────────────────────────────────

async function main() {
  console.log("🌱 Seeding database…");

  // Words
  console.log("  → Upserting 40 words…");
  let wordCount = 0;
  for (const row of wordRows) {
    const [
      id,
      word,
      category,
      gradeBandRaw,
      charCount,
      syllableCount,
      skillTagsRaw,
      errorTagsRaw,
      imageOk,
      audioOk,
      imagePrompt,
      audioText,
      sampleSentence,
      distractorsRaw,
      blankHint,
    ] = row;

    await prisma.word.upsert({
      where: { id },
      update: {},
      create: {
        id,
        word,
        category: category.trim(),
        grade_band: parseGradeBand(gradeBandRaw),
        char_count: parseInt(charCount),
        syllable_count: parseInt(syllableCount),
        skill_tags: parseSkillTags(skillTagsRaw),
        error_tags: parseStringArray(errorTagsRaw),
        image_ok: imageOk === "1",
        audio_ok: audioOk === "1",
        image_prompt: imagePrompt || null,
        audio_text: audioText || null,
        sample_sentence: sampleSentence || null,
        distractors: parseStringArray(distractorsRaw, ";"),
        blank_hint: blankHint || null,
      },
    });
    wordCount++;
  }
  console.log(`  ✓ ${wordCount} words seeded`);

  // Tasks
  console.log("  → Upserting 20 tasks…");
  let taskCount = 0;
  for (const t of tasks) {
    await prisma.task.upsert({
      where: { id: t.id },
      update: {},
      create: {
        id: t.id,
        task_type: t.task_type,
        title: t.title,
        prompt_text: t.prompt_text,
        correct_answer: t.correct_answer,
        options: t.options,
        audio_url: t.audio_url,
        image_url: t.image_url,
        primary_skill: t.primary_skill,
        secondary_skill: t.secondary_skill ?? undefined,
        level_target: t.level_target,
        error_targets: t.error_targets,
        grade_band: t.grade_band,
        difficulty: t.difficulty,
        estimated_time_seconds: t.estimated_time_seconds,
        review_after_days: t.review_after_days,
        lesson_slot_fit: t.lesson_slot_fit,
        feedback_text: t.feedback_text,
      },
    });
    taskCount++;
  }
  console.log(`  ✓ ${taskCount} tasks seeded`);

  console.log("✅ Seed complete.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
